mganss/XmlSchemaClassGenerator

README.md, XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs, XmlSchemaClassGenerator/TypeModel.cs, XmlSchemaClassGenerator/XmlSchemaClassGenerator.nuspec
Optional argument was added to avoid C# type resolution problems if user project already have `SomeProject.SomeNamespace.System` (ends with `.System`) namespace and target generated namespace set as `SomeProject.SomeNamespace.SomeSubNamespace.XsdGeneratedNamespaceBase` (via `--namespace` argument).
=> Add optional "codeTypeReferenceOptions" options to support type reference generation with "global::" prefix

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs, XmlSchemaClassGenerator/TypeModel.cs
- Add MemberVisitor delegate as an API for inspecting and/or modifying each generated member.
=> Implement #21

XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs, XmlSchemaClassGenerator/TypeModel.cs
We have an XML scheme that already contains an element named "value" and the code generation produced a conflict with the built-in property "Value" that holds the text string for the element. Added this arg to either rename or remove the in built property.
=> Add arg to override the name of the text value property

XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs, XmlSchemaClassGenerator/TypeModel.cs
Added Order property for AnyAttribute
Added new command line option --dst to apply DebuggerStepThroughAttribute to members
=> Order for Any Attribute, optional DebuggerStepThroughAttribute

XmlSchemaClassGenerator/Generator.cs
I neglected to set the Generator.OutputFolder, assuming it would just use my current directory, and as a result, got a null reference exception.  I kept thinking I was passing path filePaths to the generator, but finally realized it was the missing OutputFolder.  Using the current directory seems like a sane default.
=> Sane default in case of null OutputFolder.

XmlSchemaClassGenerator/TypeModel.cs
If you don't enable DataBinding option, and set privateSetter argument to true, no setter at all were generated. I updated the method to add a private setter.
=> #1 Fix GetAccessors method to add private setter when there's no dataBinding

XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator.Tests/XmlSchemaClassGenerator.Tests.csproj, XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator.Tests/xsd/time/time.xsd, XmlSchemaClassGenerator/CodeUtilities.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs
This PR resolves #37 
The standard XmlSerialiser **only** supports serializing xsd:time as a DateTime, so rather than making the type configurable, I have simply made a switch to enable/disabled use of DateTime for xsd:time.
It is disabled by default, to maintain compatibility with existing behavior.
=> Configurable time type

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/Generator.cs
There are times when the type is not an interface type and therefore will fail with a cast exception. This checks if the type is an interface type and only continue if it is.
=> Check if type model is interface

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/ModelBuilder.cs, XmlSchemaClassGenerator/Particle.cs, XmlSchemaClassGenerator/TypeModel.cs
The old logic for IsNullable took account of choices (marking each
element inside a choice as nullable), but only if the choice appeared as
the root of a complexType. If the choice appeared inside a sequence inside
a complexType, then ModelBuilder.GetElements would forget the fact that
a choice was ever involved.
This XSD worked as expected, with Opt1 and Opt2 being marked as
nullable:
<?xml version="1.0" encoding="utf-8" ?>
<schema elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">
<element name="Root">
<complexType>
<choice>
<element name="Opt1" type="string"/>
<element name="Opt2" type="string"/>
</choice>
</complexType>
</element>
</schema>
This XSD did not work as expected, with Opt1 and Opt2 not being marked
as nullable. This is because nullability was …
=> Properly calculate IsNullable on elements in a choice inside a sequence

README.md, XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator.sln, XmlSchemaClassGenerator/CodeUtilities.cs, XmlSchemaClassGenerator/ModelBuilder.cs, XmlSchemaClassGenerator/TypeModel.cs
Implements one part of #89.
Sorry about the whitespace changes, my IDE is set up to clean up various things automatically.
=> More fine-grained mapping for xs:integer and derived types

README.md, XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs
Added a new parameter u|enableUpaCheck to gain access to `XmlSchemaSet.CompilationSettings.EnableUpaCheck`. Default is set to true as per https://docs.microsoft.com/en-us/dotnet/api/system.xml.schema.xmlschemacompilationsettings.enableupacheck , use -u- to disable the check and avoid the following exception with `xs:any` elements:
System.Xml.Schema.XmlSchemaException: Wildcard '##other' allows element 'a_namespace_different_than_target:element', and causes the content model to become ambiguous. A content model must be formed such that during validation of an element information item sequence, the particle contained directly, indirectly or implicitly therein with which to attempt to validate each item in the sequence in turn can be uniquely determined without examining the content or …
=> Control over XmlSchemaSet checking for UPA violations

XmlSchemaClassGenerator/XmlSchemaClassGenerator.csproj, appveyor.yml, dotnet-xscgen/dotnet-xscgen.csproj, xscgen-proj/xscgen-proj.csproj
Added a new version that is NOT a .NET Global Tool, and called it `dotnet-xscgen.csproj`. This supports project-level CLI tooling by refencing `dotnet-xscgen-csproj` as a `DotNetCliToolReference`.
> It is important to note, that to make this work, a small bug fix was required in the `XmlSchemaClassGenerator-beta` package, which was swapping the order of the values in the  `TargetFrameworks` element to `netstandard2.0;net45` instead of `net45;netstandard2.0`
This functionality will allow us to use the tool inside a project-level context, for example:
```xml
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<TargetFramework>netstandard2.0</TargetFramework>
</PropertyGroup>
<Target Name="PrecompileScript" BeforeTargets="BeforeBuild">
<Exec Command="dotnet xscgen *.xsd" />
</Target> …
```
=> added new project-level cli tool to support DotNetCliToolReference

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/TypeModel.cs
I noticed that I implemented AssemblyVisible only for classes. `enum` and `interfaces` are still `public`.
This change should fix that, but one of the new tests fails because of `SourceUri` property is empty string on `attributeGroupRef`. I don't think this has something todo with the changes I did. But parse operation in the test that I use wrong.  
The xml from the text comes from a project where it is working, so that should be fine.
If someone can give me a hint what I need to change so the last test passes I would appreciate that.
=> Internal visiblility

XmlSchemaClassGenerator/TypeModel.cs
Hello.  I've been doing C# development for a variety of XML services, and I occasionally encounter a schema definition that uses numeral 1 or 0 to define true/false.
I recently have been working on a project that uses that same kind of schema definition, and your utility has been able to handle complex, interlocking definitions a lot better than any other FOSS tool that I've come across.  However, I had to make this small change to complete the code generation.
I'm submitting this PR in order to give back to the project.
=> Handle "0-1" definitions of boolean in .xsd

XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator/CodeUtilities.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs, XmlSchemaClassGenerator/TypeModel.cs
Instead of having an option to add underscore or not, let the user directly specify which prefix they want.
=> Customizable private member prefix.

XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs, XmlSchemaClassGenerator/INamingProvider.cs, XmlSchemaClassGenerator/ModelBuilder.cs, XmlSchemaClassGenerator/NamingProvider.cs
Use INamingProvider to also be able to change the class names from their
names in the XSD.
The idea is to be able to change the name of the whole class if necessary.
For example remove all underscores.
=> Add interface for NamingProvider and expand its use.

XmlSchemaClassGenerator/TypeModel.cs
The current code is not thread safe.
This is a simple fix to generate the thread safe version.
I'm not sure where you keep a change log of the changes for each version.
=> Create a thread safe OnPropertyChanged event method.

XmlSchemaClassGenerator.Tests/Compiler.cs, XmlSchemaClassGenerator.Tests/XmlSchemaClassGenerator.Tests.csproj, XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator.Tests/xsd/array-order/array-order.xsd, XmlSchemaClassGenerator/TypeModel.cs
The actual fix I've made is a small modification to `XmlSchemaClassGenerator/TypeModel.cs`. If you have time to check it out and merge, I'd really appreciate it.
It probably needs checking by someone more familiar with the code, to make sure I've done it the _right way_.
Another potential I discovered in the process is in `XmlSchemaClassGenerator.Tests/Compiler.cs`. The generator `gen` is constructed with some fields from the `generatorPrototype`, but not all. I've added `EmitOrder` (which is needed to make the test fail on the old version). Maybe this should be updated to exhaustively copy all fields, or maybe it's better to just add them as needed.
Thanks :)
=> Make EmitOrder work for arrays. Fixes #126

XmlSchemaClassGenerator.Tests/XmlSchemaClassGenerator.Tests.csproj, XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator.Tests/xml/bpmnSimple.xml, XmlSchemaClassGenerator.Tests/xsd/bpmn/BPMN20.xsd, XmlSchemaClassGenerator.Tests/xsd/bpmn/BPMNDI.xsd, XmlSchemaClassGenerator.Tests/xsd/bpmn/DC.xsd, XmlSchemaClassGenerator.Tests/xsd/bpmn/DI.xsd, XmlSchemaClassGenerator.Tests/xsd/bpmn/Semantic.xsd, XmlSchemaClassGenerator/TypeModel.cs
The title is most probably very confusing and I apologize for that. I will try to explain the issue in the following lines :)
I was using the library for generating classes from BPMN standard xsd files.
However, I have noticed a problem with substitution groups in a circular type dependency scenario, when type defines an element of same owning type which is derived in an external namespace.
The example for this can be seen in BPMNDI.xsd and DI.xsd which specify: 
1. bpmndi:BPMNShape element with type=bpmndi:BPMNShape and substitution group=di:DiagramElement
2. di:DiagramElement complex type
3. di:Plane complex type specifying sub-element of di:DiagramElement type
Since BPMNShape (and also BPMNEdge) is a derived type from a different namespace Serialization.XmlElementAttribute for …
=> Fix for wrong namespace specification of XML element attribute of derived types

XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator.Tests/NamespaceProviderTests.cs, XmlSchemaClassGenerator.Tests/XmlSchemaClassGenerator.Tests.csproj, XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/CodeUtilities.cs, XmlSchemaClassGenerator/ModelBuilder.cs, XmlSchemaClassGenerator/NamespaceProvider.cs
Namespace provider did not work correctly in cases when defined types have dependencies from other namespaces i.e. imported xsds.
This has been resolved by adding simple dependency resolver of imported schemas in ModelBuilder by prioritizing type creation from leaf schemas up to the root of the dependency tree.
Unit test is also provided to test this issue.
=> Improving namespace provider to correctly generate custom csharp namespaces 

XmlSchemaClassGenerator.Tests/Compiler.cs, XmlSchemaClassGenerator.Tests/NullableGenerationTests.cs, XmlSchemaClassGenerator.Tests/XmlSchemaClassGenerator.Tests.csproj, XmlSchemaClassGenerator.Tests/xsd/nullable/optional.xsd, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs, XmlSchemaClassGenerator/TypeModel.cs
Fixes #144 
Note the `ShouldSerialize` pattern does not work with optional xml attributes so this does not change properties marked with `XmlAttribute`
=> Added ShouldSerialize pattern for Nullable elements

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/ModelBuilder.cs
I added the XML Schema element name to the dictionary key on the assumption that an `element` with the name `MyType` is distinct from a `complexType` with the name `MyType` and that both items should have a corresponding `TypeModel`. This assumption should hold for all combinations of Schema items, such as a `simpleType` and `complexType` that share a name. Because the original element name (`xs:complexType`, `xs:element`, etc.) is encoded into the CLR type name (`XmlSchemaComplexType`, `XmlSchemaElement`, etc.), I added the CLR type name to the beginning of the dictionary key.
I also included a test that verified the existence of #50 and verifies the implemented fix.
=> Add CLR type to the dictionary key for generated TypeModels

XmlSchemaClassGenerator/ModelBuilder.cs
This change adds support for XmlSchemaLengthFacet, which indicates an exact length. This is represented as a minimum length and maximum length with the same value.
=> Add support for length facet

README.md, XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator.Tests/Compiler.cs, XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/CollectionSettersMode.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs, XmlSchemaClassGenerator/TypeModel.cs
Currently only private setters generated for collection properties and this is not supported by `SGEN.exe` while it generates serialization assembly and the message is printed:
> warning CS0200: Property or indexer 'Activities.Activity' cannot be assigned to -- it is read only
This pull request introduces `collectionSettersMode` option and allows user to choose from three different options while generating code: Private, Public, PublicWithoutConstructorInitialization. Private is the default and maintains old behavior. Public generates public setters for collection properties and PublicWithoutConstructorInitialization generates public setters and skips baking field initialization in default class constructor.
=> Implement public property setter generation for collection fields

XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator.Tests/IntegerTypeTests.cs, XmlSchemaClassGenerator/CodeUtilities.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs
First, support for the `minInclusive` and `maxExclusive` facets were added. If present, these restrictions will be used to find the CLR type with the smallest range that completely includes the bounds given by the schema will be chosen, with unsigned types given precedence. If not present, or if no CLR type fits the given range, the original logic using `totalDigits` will be used.
Second, a new configuration option has been added that allows users to specify a fallback data type. Previously, any consumer-specified data type would short-circuit the size deduction. Now, consumers can choose whether their type should be used in all cases, or if their type should be used only if no type can be deduced (replacing `string` as the fallback).
Fixes #185
=> Enhance deduction of integer type

XmlSchemaClassGenerator.Tests/VisitorTests.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs, XmlSchemaClassGenerator/TypeModel.cs
I added a new delegate `TypeVisitor` that complements the existing `MemberVisitor` delegate. It allows consumers to add custom logic regarding classes, enums, and interfaces. The new delegate is called at the end of the overridden `Generate` methods, after all other processing has been completed.
Closes #183
=> Added an optional TypeVisitor delegate

XmlSchemaClassGenerator/TypeModel.cs
that's the only place where System.ComponentModel namespace was not provided.
=> namespace added

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/ModelBuilder.cs, XmlSchemaClassGenerator/TypeModel.cs
It is valid to have an XSD enumeration with values that differs only in character case. E.g. one can use enum value 'M' for month definition and another value 'm' for minutes. To ensure that enum members are unique in generated code after name generation this commit adds positive integer postfix for each non unique enum member name: A A1 BB BB1 BB2 generated for input enum values a A bb bB BB
=> Ensure generated enum members are unique

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/TypeModel.cs
use global referencing for editorbrowsable attribute to avoid conflict with potential generated class "System"
To explain the change a bit:
- in my schema there was a class or property with the name "System" that conflicted with the System namepsace.
- when I changed the existing setting to GlobalReference I got alot more build errors for that schema
- so I decided to simply ignore the setting for this specific case, I think global referencing in general doesn't harm for the system dependencies and would make the generator more robust
=> use global referencing for editorbrowsable attribute to avoid conflict with potential generated class "System"

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/CodeUtilities.cs
For anonymous simple type CodeUtilities.GetQualifiedName returns base type name (e.g. string) and for complex types 'anyType'.
In this commit CodeUtilities.GetQualifiedName returns an element QualifiedName.
=> Fix CodeUtilities.QualifiedName for anonymous types

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/TypeModel.cs
Check for null in *Specified properties when collection not initialized in constructor
If CollectionSettersMode.PublicWithoutConstructorInitialization is set for generator then in special properties with *Specified postfix we must check if backing collection field is null to defend user from NullReferenceException.
=> Check for null in *Specified properties

README.md, XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs, XmlSchemaClassGenerator/TypeModel.cs
XmlElementAttribute.IsNullable=true forces XmlSerializer to generate empty xml elements with xs:nil=true, but elements with minOccurs < 1 can be omitted entirely.
Allow users to specify option `DoNotForceIsNullable` to skip IsNullable=true generation in XmlElement attributes for nillable elements that at the same time is nullable (minOccurs < 1 or parent element is choice).
=> Support for omitting IsNullable=true generation for nullable elements

XmlSchemaClassGenerator/CodeUtilities.cs
It's not obvious when something wrong with my `--namespace` parameter, it throws: 
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
```
So new check with ArgumentException was added.
=> Namespaces: throw ArgumentException on invalid --namespace

XmlSchemaClassGenerator/ModelBuilder.cs
When an xml element has grouped properties and emit order is configured the produced attributes do not have the correct ordering. This pr corrects that
=> Correct order propery to correctly increment on recusion

xscgen-proj/xscgen-proj.csproj, xscgen/xscgen.csproj
When using the dotnet local tool on a system with only .NET 5.0 SDK installed, the tool fails with this message:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
- The following frameworks were found:
5.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
- https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.20.04-x64
```
This PR adds the `net5.0` TFM to the global tool project files.
=> Make global tool usable with .NET 5.0 SDK

XmlSchemaClassGenerator.Tests/XmlTests.cs
On Linux and macOS, the generator writes with LF (instead of CRLF) so the normalization Regex was not matching `\r\n`.
=> Fix the `ComplexTypeWithAttributeGroupExtension` test on Linux and macOS

XmlSchemaClassGenerator.Tests/Compiler.cs, XmlSchemaClassGenerator.Tests/XmlTests.cs
Asserting with Assert.Empty / Assert.NotEmpty gives much better error messages when the assertion fails.
Before:
```
Assert.True() Failure
Expected: True
Actual:   False
at XmlSchemaClassGenerator.Tests.Compiler.Compile(String name, String[] contents) in XmlSchemaClassGenerator/XmlSchemaClassGenerator.Tests/Compiler.cs:line 152
```
After:
```
Assert.Empty() Failure
Collection: [(11144,6): error CS0579: Duplicate 'System.CodeDom.Compiler.GeneratedCodeAttribute' attribute, (11145,6): error CS0579: Duplicate 'System.SerializableAttribute' attribute, (11147,6): error CS0579: Duplicate 'System.Xml.Serialization.XmlRootAttribute' attribute, (10023,26): error CS0146: Circular base class dependency involving 'User' and 'User']
at XmlSchemaClassGenerator.Tests.Compiler.Compile(String name, …
```
=> Improve collection assertions

XmlSchemaClassGenerator.Tests/Compiler.cs, XmlSchemaClassGenerator.Tests/XmlSchemaClassGenerator.Tests.csproj, XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator.Tests/xsd/simple/any.xsd, XmlSchemaClassGenerator.Tests/xsd/simple/fields_ambiguity.xsd, XmlSchemaClassGenerator.Tests/xsd/simple/nested_type.xsd, XmlSchemaClassGenerator/CodeUtilities.cs, XmlSchemaClassGenerator/ModelBuilder.cs, XmlSchemaClassGenerator/TypeModel.cs
* any attribute is not rendered if complex type extends other complex type
* fix GlobalReference mode (`global::` gets rendered twice, collection of XmlAttribute rendered without `global::` prefix)
* fix duplicate backed value name
=> any attribute is not rendered if complex type extends other complex type

XmlSchemaClassGenerator/INamingProvider.cs, XmlSchemaClassGenerator/ModelBuilder.cs, XmlSchemaClassGenerator/NamingProvider.cs
Fixes #293.
Note that this is not a backward-compatible improvement (`INamingProvider` interface is changed). Unfortunately, I don't have any good ideas on how to make it backward-compatible (except a separate interface and new configuration option, which looks pretty silly to me).
=> Add original XSD elements to INamingProvider methods

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/ModelBuilder.cs
potentially a fix for https://github.com/mganss/XmlSchemaClassGenerator/issues/303
This is only a failing unit test for now
=> Avoid XmlElementAttribute creation for Properties created via a ref=""

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/TypeModel.cs
Fixes #325.
Correct logic was already implemented in the function used to generate interfaces for "normal" groups. This logic was moved to a property so that it can be used to generate correct interfaces for both attribute groups and "normal" groups.
=> Fix invalid interface generated for attribute group containing attribute with list type

XmlSchemaClassGenerator.Tests/FileOutputWriterTests.cs
All tests would fail because paths are made of / instead of \ on Linux and macOS.
Also the "Confiruation" typo was fixed.
=> Fix FileOutputWriterTests on non-Windows platforms

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/CodeUtilities.cs, XmlSchemaClassGenerator/ModelBuilder.cs, XmlSchemaClassGenerator/RestrictionModel.cs, XmlSchemaClassGenerator/TypeModel.cs
Fixes #332 and #333 
While I was at it, I couldn't help myself from modernising and tidying up the code:
- Avoid hard-coded strings.
- `new()`
- pattern matching
- helper methods to avoid duplication
Removed about 500 lines of code.
All tests passing except `XsdElsterDatenabholung5.CanCompileClasses` due to missing files.
=> Fixed NRT issues and tidied code.

XmlSchemaClassGenerator/CodeUtilities.cs
=> Keyword types when using `--compactTypeNames`

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/ModelBuilder.cs
Fixes #339.
Previously only direct children of choices would be forced to nullable (see how [choices](https://github.com/mganss/XmlSchemaClassGenerator/tree/8204bee66d88dd612a44cd3cf8f1a7b3a8a539e6#choice) are handled in XmlSchemaClassGenerator). This pull request adds support to force nested descendants of choices to nullable if needed.
=> Add support for nested non-nullable choice members

XmlSchemaClassGenerator/Extensions.cs, XmlSchemaClassGenerator/IXmlSchemaNode.cs, XmlSchemaClassGenerator/ModelBuilder.cs, XmlSchemaClassGenerator/TypeModel.cs
When applying the latest release to our project, all of the NRT warnings were fixed except one. The difference for this is one was that the complex type was referenced rather than inline, and just changing that has removed the nullable attributes, however since it is also never null in the initial state, I thought this change should be made. There's no rush to complete this, and I think it may need some more thought.
Combine `IsCollection`, `IsArray` and `IsList` into `IsEnumerable`, and use for nullable attribute prevention.
Moved `GetSet` into `GetAccessors` to avoid nested ternary
Tidied up `ModelBuilder` by encapsulating common groups of property setters on `PropertyModel`, using `IXmlSchemaNode`.
=> Not-Null Arrays when using `--nullableReferenceAttributes`

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/ModelBuilder.cs
Starting from v2.0.711 Interfaces are not more implemented in generated code
=> fix interface for attributeGroup

XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator.Tests/Compiler.cs, XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs, XmlSchemaClassGenerator/ModelBuilder.cs
Sometimes enums are not desirable and is more of a complication than help. In these cases it is nice to have an option to turn off enum creation and rather create the property as string.
=> Implemented option to treat enumeration as string instead of creating enum

README.md, XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator/EnumerableExtensions.cs, XmlSchemaClassGenerator/INamingProvider.cs, XmlSchemaClassGenerator/ModelBuilder.cs, XmlSchemaClassGenerator/NamingProvider.cs, XmlSchemaClassGenerator/NamingProviders/SubstituteNamingProvider.cs
A need to specify alternate/replacement names for types and/or properties during generation, specifically from the command line.
- Added new `NamingProvider` implementation, `SubstituteNamingProvider`, which can store a dictionary of generated names and an alternate to substitute with.
- Updated the `INamingProvider` to add two specific `Type`-based methods for `PropertyNameFromAttribute` and `PropertyNameFromElement`, to ensure that custom implementors can split the implementation accordingly.
- Updated `XmlSchemaClassGenerator.Console` to accept new command line options:
- `--typeNameSubstitute`: For each instance, the `{generated}={substituted}` value is added to a collection.
- `--typeNameSubstituteFile`: For each instance, the containing `{generated} = {substituted}` lines are added …
=> Add a dedicated substitution naming provider

XmlSchemaClassGenerator.Tests/XmlTests.cs, XmlSchemaClassGenerator/CodeUtilities.cs
Hi,
the ToPascalCase login is not able to manage cases like these:
- MY_FIRST_CLASS
- MY_PROPERTY
- ...
For this reason I have changed the ToPascalCase logic using [chviLadislav](https://stackoverflow.com/users/5612780/chviladislav) contribution found at [how-can-i-convert-text-to-pascal-case](https://stackoverflow.com/questions/18627112/how-can-i-convert-text-to-pascal-case).
Please check the changes and pull the request if you like.
Thank you and best regards,
Filippo
=> Substitution of ToPascalCase logic with a more general one

XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator.Tests/Compiler.cs, XmlSchemaClassGenerator.Tests/FileOutputWriterTests.cs, XmlSchemaClassGenerator/FileOutputWriter.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs
Add option for separate namespace hierarchy by folder (works if `SeparateClasses` is true). Default is false.
With this option, class `PurchaseOrderType` in namespace `Generator.Prefix` places in: `Generator/Prefix/PurchaseOrderType.cs`
=> Add option for separate namespace hierarchy by folder

README.md, XmlSchemaClassGenerator.Console/Program.cs, XmlSchemaClassGenerator.Tests/DateTimeTypeTests.cs, XmlSchemaClassGenerator/CodeUtilities.cs, XmlSchemaClassGenerator/Generator.cs, XmlSchemaClassGenerator/GeneratorConfiguration.cs
Since the .NET XmlSerializer now also supports serializing to and from DateTimeOffset, an option has been added to use DateTimeOffset for xs:datetime properties.
Closes #171 
Relates to #458
=> Allow generation of DateTimeOffset properties for xs:dateTime

XmlSchemaClassGenerator.Tests/DateTimeTypeTests.cs, XmlSchemaClassGenerator/TypeModel.cs
When generating a C# class for an XSD that has datetime properties, and the option to generate `DateTimeOffset` properties for those datetime elements, do not specify the `DataType` attribute on the XmlElementAttribute
Fixes #465
=> Do not generate DataType property in Xml serialization property

XmlSchemaClassGenerator.Console/Program.cs
The value of the namingscheme parameter was ignored, because the parser did not expect a value after `--namingScheme`.
=> Fix `namingscheme` parameter

XmlSchemaClassGenerator.Console/Program.cs
When --namingScheme argument and --typeNameSubstitute aregument are provided at the same time, the --namingScheme is ignored and always uses PascalCase.
`--typeNameSubstitute=T:OriginalName=NewName--namingScheme=Direct`
Closes #532
=> Fix "namingScheme" argument is ignored when "typeNameSubstitute" argument is provided in console
